In [2]:
import numpy as np
import tensorflow as tf

/is/sg/klee/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [169]:
dim_z = 5
z = np.random.normal(size=(5))

tf.reset_default_graph()

idxs_feed = [1,3,-1,-1,6]

idxs_ph = tf.placeholder(tf.int32, shape=dim_z, name='indexes')    
idxs_one_hot = tf.one_hot(idxs_ph, depth=dim_z)        
feed_dict = {idxs_ph:idxs_feed}

tmp = tf.not_equal(idxs_ph, -1) 
idx_pos = tf.where(tmp)
beauty = tf.gather_nd(idxs_one_hot, idx_pos) 
beauty = tf.reduce_sum(beauty, axis=0)

with tf.Session() as sess:    
    print( sess.run(idx_pos, feed_dict=feed_dict) )    
    print( sess.run(beauty, feed_dict=feed_dict) )    
        
    #print(z)

[[0]
 [1]
 [4]]
[0. 1. 0. 1. 0.]


In [194]:
# Take out negative dimension and assign values to them
v = tf.Variable([0]*dim_z)
init = tf.global_variables_initializer()
cond_neg = tf.equal(idxs_ph, -1) 
v_ = tf.ones_like(v)
cond_assign = v.assign(tf.where(cond_neg, v_, v))
cond_neg_digit = tf.cast(cond_neg, tf.float32)

with tf.Session() as sess:
    sess.run(init)    
    a = sess.run(v)
    print('before: {}'.format(a))
    b = sess.run(cond_assign ,feed_dict=feed_dict)
    print('after: {}'.format(b))
    c = sess.run(cond_neg ,feed_dict=feed_dict)
    print('cond: {}'.format(c))
    d = sess.run(cond_neg_digit, feed_dict=feed_dict)
    print(d)
    


before: [0 0 0 0 0]
after: [0 0 1 1 0]
cond: [False False  True  True False]
[0. 0. 1. 1. 0.]


- reference: https://stackoverflow.com/questions/39045797/conditional-assignment-of-tensor-values-in-tensorflow

### Prototype

In [11]:
import tensorflow as tf
# Testing the concatination
tf.reset_default_graph()
v0 = [1,2,3,4,5]
v2aug = tf.constant(v0, dtype=tf.float32)
i = 1
l = len(v0)
with tf.Session() as sess:
    v2aug[:i+1]
    d_rem = l - (i+1)
    zeros = tf.zeros(shape=d_rem)    
    v2 = tf.concat([v2aug, zeros], axis=0)
    print(sess.run(v2))
    print(v2.get_shape())

[1. 2. 3. 4. 5. 0. 0. 0.]
(8,)


In [214]:
tf.reset_default_graph()
v0 = [1,2,3,4,5]
v2aug = tf.constant(v0, dtype=tf.float32)
i = 1
l = len(v0)
with tf.Session() as sess:
    x = sess.run(v2aug)
    print(x)
    
    

[1. 2. 3. 4. 5.]
